books/urls.py
from django.urls import path
from . import views


app_name = 'books'
urlpatterns = [
    path('', views.index, name='index'),
    path('genres/', views.genres, name='genres'),
    path('book/<slug:book_slug>/', views.book, name='book'),
    path('genre/<slug:genre_slug>/', views.genre, name='genre'),
    path('favorites/', views.favorites, name='favorites'),
    path('favorite/<slug:book_slug>/', views.favorite, name='favorite'),
    path('add-book/', views.add_book, name='add_book'),
    path('book/<slug:book_slug>/edit', views.edit_book, name='edit_book'),
    path('book/<slug:book_slug>/add-review/', views.add_review, name='add_review'),
]

library/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('', include('books.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

users/urls.py
"""Определяет схемы URL для пользователей"""

from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    # Включить URL авторизации по умолчанию
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации
    path('register/', views.register, name = 'register'),
    # Авторизация
    #path('login/', views.LoginView.as_view(), name='login'), 
    # Выход
    #path('logout/', views.LogoutView.as_view(), name='logout'), 
    # Смена пароля
    #path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # Сообщение об успешном изменении пароля
    #path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # Восстановление пароля
    #path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    # Сообщение об отправке ссылки для восстановления пароля
    #path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # Вход по ссылке для восстановления пароля
    #path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # Сообщение об успешном восстановлении пароля
    #path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

books/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.db.models import UniqueConstraint
from django.core.validators import MinValueValidator, MaxValueValidator
from .utils import unique_slugify


class Author(models.Model):
    name = models.CharField(max_length=200, verbose_name='Имя автора', unique=True)
    slug = models.SlugField(max_length=200,  verbose_name='Slug_author', unique=False, db_index=True)
    description = models.TextField(verbose_name='Описание', blank=True, null=True)

    class Meta:
        ordering = ('-name',)
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'

    def __str__(self) -> str:
        return self.name
    
    def save(self, *args, **kwargs):
        """Сохранение полей модели при их отсутствии заполнения."""
        if not self.slug:
            self.slug = unique_slugify(self, self.name)
        super().save(*args, **kwargs)

class Genre(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название жанра', unique=True)
    color = models.CharField(max_length=7, verbose_name='Цвет')
    slug = models.SlugField(max_length=200, verbose_name='Slug_genre', unique=True, db_index=True)

    class Meta:
        ordering = ('-name',)
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'

    def __str__(self) -> str:
        return self.name
    
    def save(self, *args, **kwargs):
        """Сохранение полей модели при их отсутствии заполнения."""
        if not self.slug:
            self.slug = unique_slugify(self, self.name)
        super().save(*args, **kwargs)


class Book(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название книги')
    authors = models.ManyToManyField(Author, verbose_name='Автор', through='AuthorBook', blank=True)
    description = models.TextField(verbose_name='Описание')
    year_of_issue = models.IntegerField(validators=[MinValueValidator(4), MaxValueValidator(datetime.datetime.now().year)], verbose_name='Год выпуска')
    availability = models.IntegerField(validators=[MaxValueValidator(100)], verbose_name='Наличие')
    image = models.ImageField(upload_to='books/image/', blank=True, null=True, verbose_name='Изображение')
    genres = models.ManyToManyField(Genre, blank=True, verbose_name='Жанры', through='GenreBook')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')
    slug = models.SlugField(max_length=200, verbose_name='Slug_book', unique=True, db_index=True)
    
    class Meta:
        ordering = ('-name',)
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'

    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.name
    
    def save(self, *args, **kwargs):
        """Сохранение полей модели при их отсутствии заполнения."""
        if not self.slug:
            self.slug = unique_slugify(self, self.name)
        super().save(*args, **kwargs)
    
    def average_rating(self):
        """Вычисление средней оценки книги"""
        reviews = self.reviews.all()
        if reviews.exists():
            total_rating = sum(review.rating for review in reviews)
            return round(total_rating / reviews.count(), 1)
        return None
    
    def review_count(self):
        """Возвращение кол-ва отзывов к книге"""
        return self.reviews.count()



class GenreBook(models.Model):
    book = models.ForeignKey(Book, null=True, on_delete=models.SET_NULL, verbose_name='Книга')
    genre = models.ForeignKey(Genre, null=True, on_delete=models.SET_NULL, verbose_name='Жанр')

    class Meta:
        constraints = [UniqueConstraint
                       (fields=['book', 'genre'],
                        name='book_genre_unique')]
        verbose_name = 'Жанр-Книга'
        verbose_name_plural = 'Жанры-Книга'


class AuthorBook(models.Model):
    book = models.ForeignKey(Book, null=True, on_delete=models.SET_NULL, verbose_name='Книга')
    author = models.ForeignKey(Author, null=True, on_delete=models.CASCADE, verbose_name='Автор')

    class Meta:
        constraints = [UniqueConstraint
                       (fields=['book', 'author'],
                        name='book_author_unique')]
        verbose_name = 'Автор-Книга'
        verbose_name_plural = 'Авторы-Книга'


class Favorite(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Пользователь',
        related_name='favorites'
    )
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        verbose_name='Книга',
        related_name='favorites'
    )

    class Meta:
        constraints = [UniqueConstraint(
            fields=['user', 'book'],
            name='user_favorite_unique')]
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранное'

    def __str__(self) -> str:
        return f'{self.user} - {self.book}'


class Review(models.Model):
        book = models.ForeignKey(
            Book,
            on_delete=models.CASCADE,
            verbose_name='Книга',
            related_name='reviews'
        )
        user = models.ForeignKey(
            User,
            on_delete=models.CASCADE,
            verbose_name='Пользователь',
            related_name='reviews'
        )
        rating = models.PositiveIntegerField(
            choices = [(i, i) for i in range(1, 6)],
            verbose_name='Оценка'
        )
        comment = models.TextField(blank=True, null=True, verbose_name='Отзыв')
        created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    
        class Meta:
            verbose_name = "Отзыв"
            verbose_name_plural = "Отзывы"

        def __str__(self):
            return f"Отзыв на {self.book.name} от {self.user.username}"  

books/forms.py
from django import forms
from .models import Book, Author

class BookForm(forms.ModelForm):
    authors = forms.CharField(
        label = "Авторы",
        widget = forms.TextInput(attrs={'placeholder': 'Введите имена авторов через запятую'}),
        help_text= "Если автора нет в базе данных, он будет создан автоматически"
    )

    class Meta:
        model = Book
        fields = ['name', 'authors', 'description', 'year_of_issue', 'availability', 'genres', 'image',]
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
        }
    
    def __init__(self, *args, **kwargs):
        """
        Переопределяем метод __init__, чтобы предзаполнить поле authors.
        """
        super().__init__(*args, **kwargs)
        if self.instance.pk:  # Если книга уже существует (режим редактирования)
            # Преобразуем список авторов в строку через запятую
            self.initial['authors'] = ', '.join(self.instance.authors.values_list('name', flat=True))
            
    def clean_authors(self):
        author_names = self.cleaned_data['authors'].split(',')
        authors = []
        for name in author_names:
            name = name.strip()
            if name:
                author, created = Author.objects.get_or_create(name=name)
                authors.append(author)
        return authors

books/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from .models import Genre, Book, Author, AuthorBook, Favorite, Review
from .forms import BookForm


def index(request):
    """Домашняя страница"""
    return render(request, 'books/index.html')

def genres(request):
    """Выводит список жанров."""
    genres = Genre.objects.order_by('name')
    context = {'genres': genres}
    return render(request, 'books/genres.html', context)

def genre(request, genre_slug):
    """Выводит один жанр и список книг по этому жанру."""
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = BookForm()
    
    images = Book.objects.all()
    genre = Genre.objects.get(slug=genre_slug)
    #author = AuthorBook.author_set.all()
    books = genre.book_set.order_by('-time_create') 
    favorite_slugs = request.user.favorites.values_list('book__slug', flat=True)
    
    return render(request, 'books/genre.html', {
        'genre': genre,
        'books': books,
        'favorite_slugs': favorite_slugs
    })

def book(request, book_slug):
    """Страница конкретной книги."""
    book = get_object_or_404(Book, slug=book_slug)
    is_favorite = False

    # Проверяем, добавлена ли книга в избранное (только для авторизованных пользователей)
    if request.user.is_authenticated:
        is_favorite = book.favorites.filter(user=request.user).exists()

    return render(request, 'books/book.html', {'book': book, 'is_favorite': is_favorite})

@login_required
def favorite(request, book_slug):
    """Добавляет или удаляет книгу из списка избранного пользователя."""
    if request.method == 'POST':
        book = get_object_or_404(Book, slug=book_slug)
        user = request.user

        # Проверяем, есть ли уже эта книга в избранном
        favorite, created = Favorite.objects.get_or_create(user=user, book=book)

        if not created:
            # Если книга уже в избранном, удаляем её
            favorite.delete()
            messages.success(request, 'Книга удалена из избранного.')
        else:
            # Если книга добавлена в избранное
            messages.success(request, 'Книга добавлена в избранное.')

        # Определяем, куда перенаправлять пользователя
        referer = request.META.get('HTTP_REFERER', '/')
        if '/genre/' in referer:
            # Если пользователь находится на странице жанра
            return redirect(f'/genre/{book.genres.first().slug}/#scroll-to-here')
        elif '/book/' in referer:
            # Если пользователь находится на персональной странице книги
            return redirect(f'/book/{book.slug}/#scroll-to-here')
        elif '/favorites/' in referer:
            # Если пользователь находится на персональной странице книги
            return redirect(f'/favorites/')
        else:
            # В остальных случаях перенаправляем на главную страницу
            return redirect('/')

@login_required
def favorites(request):
    """Отображает список книг, добавленных в избранное текущим пользователем."""
    favorite_books = request.user.favorites.all()  # Получаем все избранные книги пользователя
    return render(request, 'books/favorites.html', {'favorite_books': favorite_books})

@login_required
@user_passes_test(lambda u: u.is_superuser)
def add_book(request):
    """Отображение формы для добавления новой книги."""
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save(commit=False)
            book.save()
            book.authors.set(form.cleaned_data['authors'])
            book.genres.set(form.cleaned_data['genres'])
            book.save()
            return redirect('books:book', book_slug=book.slug)
    
    else:
        form = BookForm()
    
    return render(request, 'books/add_book.html', {'form': form})

@login_required
@user_passes_test(lambda u: u.is_superuser)
def edit_book(request, book_slug):
    """Отображает форму для редактирования существующей книги."""
    book = get_object_or_404(Book, slug=book_slug)

    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            form.save()
            return redirect('books:book', book_slug=book.slug)
    else:
        form = BookForm(instance=book)

    return render(request, 'books/edit_book.html', {'form': form, 'book': book})

@login_required
def add_review(request, book_slug):
    """Добавление отзыва к книге"""
    book = get_object_or_404(Book, slug=book_slug)

    if request.method == 'POST':
        rating = request.POST.get('rating')
        comment = request.POST.get('comment')

        if not Review.objects.filter(book=book, user=request.user).exists():
            Review.objects.create(
                book=book,
                user=request.user,
                rating=rating, 
                comment=comment
            )
            messages.success(request, 'Ващ отзыв успешно добавлен.')
        else:
            messages.success(request, 'Вы уже оставляли отзыв на эту книгу.')

    return redirect('books:book', book_slug=book.slug)

books/templates/books/add_book.html
{% extends "base.html" %}

{% block title %} Добавить книгу {% endblock %}

{% block content %}

<div class="container">
  <h2>Добавить новую книгу</h2>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mb-3">
      <label for="{{ form.name.id_for_label }}" class="form-label">Название</label>
      {{ form.name }}
    </div>

    <div class="mb-3">
      <label for="{{ form.authors.id_for_label }}" class="form-label">Авторы</label>
      {{ form.authors }}
      <small class="form-text text-muted">{{ form.authors.help_text }}</small>
    </div>

    <div class="mb-3">
      <label for="{{ form.genres.id_for_label }}" class="form-label">Жанры</label>
      {{ form.genres }}
    </div>

    <div class="mb-3">
      <label for="{{ form.description.id_for_label }}" class="form-label">Описание</label>
      {{ form.description }}
    </div>

    <div class="mb-3">
      <label for="{{ form.image.id_for_label }}" class="form-label">Изображение</label>
      {{ form.image }}
    </div>

    <div class="mb-3">
      <label for="{{ form.year_of_issue.id_for_label }}" class="form-label">Год выпуска</label>
      {{ form.year_of_issue }}
    </div>

    <div class="mb-3">
      <label for="{{ form.availability.id_for_label }}" class="form-label">Наличие</label>
      {{ form.availability }}
    </div>

    <button type="submit" class="btn btn-primary">Добавить книгу</button>
  </form>
</div>

{% endblock content %}

books/templates/books/book.html
{% extends "base.html" %}

{% block title %} {{ book.name }} {% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <!-- Левая колонка: Изображение книги -->
    <div class="col-md-3">
      {% if book.image %}
        <img src="{{ book.image.url }}" class="img-thumbnail w-100">
      {% else %}
        <p>Изображение не загружено</p>
      {% endif %}
    </div>

    <!-- Средняя колонка: Информация о книге -->
    <div class="col-md-6">
      <h5 class="card-title">{{ book.name }}</h5>

      <!-- Авторы -->
      <p class="card-text">
        <b>Автор:</b>
        {% if book.authors.count == 1 %}
          <a href="#">{{ book.authors.first.name }}</a>
        {% else %}
          <span class="author-tooltip">
            <a href="#">{{ book.authors.first.name }}</a> и др.
            <span class="tooltip-text">
              {% for author in book.authors.all %}
                {{ author.name }}{% if not forloop.last %}, {% endif %}
              {% endfor %}
            </span>
          </span>
        {% endif %}
      </p>

      <!-- Жанры -->
      <p class="card-text">
        <b>Жанры:</b>
        {% for genre in book.genres.all %}
          <a href="{% url 'books:genre' genre.slug %}" class="text-decoration-none text-dark">{{ genre }}</a>{% if not forloop.last %}, {% endif %}
        {% empty %}
          Нет жанров
        {% endfor %}
      </p>

      <!-- Рейтинг и количество отзывов -->
      <p class="card-text">
        <i class="fas fa-star text-warning"></i>
        {% if book.average_rating > 0 %}
          {{ book.average_rating }}
        {% else %}
          Нет оценок
        {% endif %}
        (<a href="#reviews" class="text-decoration-none text-dark">{{ book.review_count }} отзыв{{ book.review_count|pluralize:"ов" }}</a>)
      </p>

      <!-- О книге -->
      <p><b>О книге:</b></p>
      <p>{{ book.description|linebreaks }}</p>

      <!-- Отзывы -->
      <div id="reviews" class="mt-4">
        <h4>Отзывы</h4>
        {% if book.reviews.exists %}
          <ul class="list-group">
            {% for review in book.reviews.all %}
              <li class="list-group-item">
                <p><b>{{ review.user.first_name }}</b> ({{ review.created_at|date:"d.m.Y" }}):</p>
                <p>Оценка: {{ review.rating }}</p>
                <p>{{ review.comment|default:"Без комментария" }}</p>
              </li>
            {% endfor %}
          </ul>
        {% else %}
          <p>Пока нет отзывов.</p>
        {% endif %}
      </div>

      <!-- Форма добавления отзыва -->
      {% if request.user.is_authenticated %}
        <form method="post" action="{% url 'books:add_review' book.slug %}" class="mt-3">
          {% csrf_token %}
          <div class="mb-3">
            <label for="id_rating" class="form-label">Оценка</label>
            <select name="rating" id="id_rating" class="form-select">
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
              <option value="5">5</option>
            </select>
          </div>
          <div class="mb-3">
            <label for="id_comment" class="form-label">Отзыв</label>
            <textarea name="comment" id="id_comment" class="form-control" rows="3"></textarea>
          </div>
          <button type="submit" class="btn btn-primary">Оставить отзыв</button>
        </form>
      {% else %}
        <p class="text-muted small">
          Чтобы оставить отзыв, пожалуйста,
          <a href="{% url 'users:login' %}">войдите в аккаунт</a>
          или <a href="{% url 'users:register' %}">зарегистрируйтесь</a>.
        </p>
      {% endif %}
    </div>

    <!-- Правая колонка: Кнопки -->
<div class="col-md-3">
  <div class="text-center mt-4"> <!-- Добавляем отступ сверху и выравнивание по центру -->
    <!-- Кнопка "Добавить в избранное" или "Удалить из избранного" -->
    <form method="post" action="{% url 'books:favorite' book.slug %}" class="d-inline mb-3">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary w-75"> <!-- Уменьшаем ширину кнопки -->
        <i class="fas fa-heart {% if is_favorite %}text-danger{% else %}text-secondary{% endif %}"></i>
        {% if is_favorite %}
          Удалить из избранного
        {% else %}
          Добавить в избранное
        {% endif %}
      </button>
    </form>

    <!-- Кнопка "Редактировать книгу" для суперпользователя -->
    {% if request.user.is_superuser %}
      <a href="{% url 'books:edit_book' book.slug %}" class="btn btn-outline-secondary w-75 mt-3">
        Редактировать
      </a>
    {% endif %}
  </div>
</div>

<!-- Отображение сообщений -->
{% if messages %}
  <div class="container mt-3">
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
  </div>
{% endif %}
{% endblock content %}

books/templates/books/edit_book.html
{% extends "base.html" %}

{% block title %} Редактировать книгу "{{ book.name }}" {% endblock %}

{% block content %}

<div class="container">
  <h2>Редактировать книгу "{{ book.name }}"</h2>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="mb-3">
      <label for="{{ form.name.id_for_label }}" class="form-label">Название</label>
      {{ form.name }}
    </div>

    <div class="mb-3">
      <label for="{{ form.authors.id_for_label }}" class="form-label">Авторы</label>
      {{ form.authors }}
      <small class="form-text text-muted">{{ form.authors.help_text }}</small>
    </div>

    <div class="mb-3">
      <label for="{{ form.genres.id_for_label }}" class="form-label">Жанры</label>
      {{ form.genres }}
    </div>

    <div class="mb-3">
      <label for="{{ form.description.id_for_label }}" class="form-label">Описание</label>
      {{ form.description }}
    </div>

    <div class="mb-3">
      <label for="{{ form.image.id_for_label }}" class="form-label">Изображение</label>
      {{ form.image }}
    </div>

    <div class="mb-3">
      <label for="{{ form.year_of_issue.id_for_label }}" class="form-label">Год выпуска</label>
      {{ form.year_of_issue }}
    </div>

    <div class="mb-3">
      <label for="{{ form.availability.id_for_label }}" class="form-label">Наличие</label>
      {{ form.availability }}
    </div>

    <button type="submit" class="btn btn-primary">Сохранить изменения</button>
  </form>
</div>

{% endblock content %}

books/templates/books/favorites.html
{% extends "base.html" %}

{% block title %} Избранное {% endblock %}

{% block content %}
<div class="container">
  <h2>Избранные книги</h2>
  {% if favorite_books %}
    <ul class="list-group">
      {% for favorite in favorite_books %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <!-- Название книги -->
          <a href="{% url 'books:book' favorite.book.slug %}" class="text-decoration-none text-dark">
            {{ favorite.book.name }}
          </a>

          <!-- Кнопка удаления из избранного -->
          <form method="post" action="{% url 'books:favorite' favorite.book.slug %}" class="d-inline">
            {% csrf_token %}
            <button type="submit" class="btn p-0 border-0" style="background: none;">
              <i class="fas fa-heart text-danger"></i> <!-- Заполненное сердечко -->
            </button>
          </form>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Вы пока не добавили ни одной книги в избранное.</p>
  {% endif %}
</div>
{% endblock content %}

books/templates/books/genre.html
{% extends "base.html" %}

{% block title %} {{ genre.name }} {% endblock %}

{% block content %}
<div class="container">
  <h2>Книги жанра "{{ genre.name }}"</h2>
  <div class="row row-cols-1 row-cols-md-5 g-4">
    {% for book in books %}
      <div class="col">
        <div class="card h-100 text-center">
          <!-- Обложка книги -->
          <div class="card-img-top position-relative">
            {% if book.image %}
            <a href="{% url 'books:book' book.slug %}">
              <img src="{{ book.image.url }}" class="card-img-top img-fluid" alt="{{ book.name }}">
            </a>
            {% else %}
              <div class="card-img-top bg-light d-flex justify-content-center align-items-center" style="height: 200px;">
                <p class="text-muted">Нет обложки</p>
              </div>
            {% endif %}
          </div>

          <!-- Название книги -->
          <div class="card-body">
            <h5 class="card-title fw-bold">
              <a href="{% url 'books:book' book.slug %}" class="text-decoration-none text-dark">
                {{ book.name }}
              </a>
            </h5>

            <!-- Автор(ы) и кнопка избранного -->
            <div class="d-flex justify-content-between align-items-center">
              <p class="card-text text-secondary mb-0">
                {% if book.authors.count == 1 %}
                  {{ book.authors.first.name }}
                {% else %}
                  {{ book.authors.first.name }} и др.
                {% endif %}
              </p>

              <!-- Кнопка избранного -->
              <form method="post" action="{% url 'books:favorite' book.slug %}" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="btn p-0 border-0" style="background: none;">
                  <i class="{% if book.slug in favorite_slugs %}fas fa-heart text-danger{% else %}far fa-heart text-secondary{% endif %}"></i>
                </button>
                <div id="scroll-to-here"></div>
              </form>
            </div>
          </div>
        </div>
      </div>
    {% empty %}
      <p>По этому жанру пока нет книг.</p>
    {% endfor %}
  </div>
</div>
{% endblock content %}

books/templates/books/genres.html
{% extends "base.html" %}

{% block title %} Жанры {% endblock %}

  {% block content %}
    <p>Жанры</p>
      <ul>
        {% for genre in genres %}
          <li><a href="{% url 'books:genre' genre.slug %}">{{ genre }}</a></li>
          {% empty %}
          <li>Сейчас нет жанров</li>
        {% endfor %}
      </ul>
  {% endblock content %}

books/templates/books/index.html
{% extends "base.html" %}

{% block title %}Библиотека им. Кокошки{% endblock %}

{% block content %}
<p>Данный вебсайт поможет вам найти книги в данной библиотеке, посмотреть наличие, взять книгу, вернуть книгу, продлить пользование</p>
{% endblock content %}